"""Model the Buckler response payloads the monitor reads."""

# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2026-01-18T21:22:03+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CharacterWinRate(BaseModel):
    """Represent one character's current Buckler battle statistics."""

    battle_count: int
    character_id: int
    win_count: int
    character_name: str
    character_alpha: str
    character_tool_name: str
    character_sort: int


class WinRateResponse(BaseModel):
    """Represent the validated character-win-rate API response."""

    character_win_rates: list[CharacterWinRate]


# The models below are written by hand from responses captured on 2026-10-06.
# They declare only the fields the monitor reads.


class MasterPassCharacter(BaseModel):
    """Represent one character's points on a season's Master Pass."""

    character_id: int
    point: int


class MasterPass(BaseModel):
    """Represent one season's Master Pass for the logged-in account."""

    season_id: int
    # Buckler's own page checks this for null before reading it, so a pass
    # without a character list is a shape it expects to see.
    characters: list[MasterPassCharacter] | None = None


class MasterPassList(BaseModel):
    """Represent the Master Pass seasons Buckler returned."""

    master_rate_pass_list: list[MasterPass]


class MasterPassResponse(BaseModel):
    """Represent the validated Master Pass API response."""

    message_list: MasterPassList = Field(alias="messageList")


class LoginUser(BaseModel):
    """Represent the account a set of Buckler session cookies belongs to."""

    short_id: int = Field(alias="shortId")
    # False, with a zero short ID, when the cookies are not logged in.
    flg: bool


class LoginDataResponse(BaseModel):
    """Represent the validated login-data API response."""

    login_user: LoginUser = Field(alias="loginUser")
