"""Model the Buckler character-win-rate response payload."""

# generated by datamodel-codegen:
#   filename:  response.json
#   timestamp: 2026-01-18T21:22:03+00:00

from __future__ import annotations

from pydantic import BaseModel


class CharacterWinRate(BaseModel):
    """Represent one character's current Buckler battle statistics."""

    battle_count: int
    character_id: int
    win_count: int
    character_name: str
    character_alpha: str
    character_tool_name: str
    character_sort: int


class WinRateResponse(BaseModel):
    """Represent the validated character-win-rate API response."""

    character_win_rates: list[CharacterWinRate]
